title = "Future of Coding Weekly 2024/02 Week 1"
from = "Mariano Guerra <mariano@marianoguerra.org>"
base_url = "https://newsletter.futureofcoding.org/join/"

[html]

prefix = '<div style="max-width:80ch;margin:auto;font-size:14pt;line-height:1.4em;">'
suffix = '<p><a href="{{unsubscribe_link}}">unsubscribe</a></p></div>'

[text]

suffix = "\n\nTo unsubscribe: {{unsubscribe_link}}"
