
dist: clean-dist build-release
	cp target/release/foc .

clean-dist:
	rm -rf target

build-release:
	cargo build --release

ubuntu-2004-shell:
	docker run -it -v .:/artifacts ubuntu-foc:20-04

ubuntu-2004-release:
	docker run -i -u $(whoami) --rm -v .:/artifacts ubuntu-foc:20-04 bash -c 'cd /artifacts; just dist'

docker-build-ubuntu-2004:
	docker build --no-cache --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg UNAME=$(whoami) -t ubuntu-foc:20-04 resources/containers/ubuntu/

upload-foc:
	scp foc foc@newsletter.futureofcoding.org:/home/foc/foc-new
	ssh foc@newsletter.futureofcoding.org "cp foc foc-cur"
