
ubuntu-2004-shell:
	docker run -it -v .:/project ubuntu-foc:20-04

docker-build-ubuntu-2004:
	docker build --no-cache --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg UNAME=$(whoami) -t ubuntu-foc:20-04 resources/containers/ubuntu/
